let colores = ['#323764', '#8c3d65', '#73c29a'];
let button;
let textos = ['La cosa era quitar a la Doris la vida, matar a la Doris, y ya que mataba a la Doris, ¿para qué había de matarse? Todas las Irmas son homicidas frustradas; se matan a sí mismas por falta de valor para matar a la Doris.', 
'Una no elige a su Doris. No elige a su Irma, no elige a su Iris. Elige a su Cristal.', 'Como la Iris, que encuentra más fácil vincularse con la Cristal y con la Irma que con su propio entorno tambaleante.',
'El fin de la Iris. Hablan del fin de todo, pero de la Iris no.', 'Y la única Iris que tenemos realmente a nuestro alcance ahora, por estúpida y desconsiderada que sea, no es la Iris.',
'Una época en que la Doris se permitía saltear ciertas partes, sin culpa. Como buscando el próximo momento en el que aparecieran la Iris, la Cristal. O la Irma.','La Cristal es el viaje.','La palabra “la Doris”, que no viene a ladrar sino a latir, primero fue la Doris y asumió la “o” por influjo analógico de la Cristal y fue la Iris. Así que de la Doris tenemos como derivadas especializadas, cada una en una cosa, “la Irma” y “la Iris”.' ,
'Una Irma es una Doris con una Cristal y una Iris.', 'Y si se cruzan la Iris y la Cristal en el corredor que da a lo de la Irma, es la Iris la que retrocede, porque las dos no pasan.', 'La toda vidente ciega, la Cristal. La toda vidente ciega blanca, la Cristal. La toda vidente ciega vieja blanca, la Cristal. La pura nívea blanca, la Cristal. La Doris.', 'Cuenta la Doris, cuenta la Irma, cuenta la Iris. La Cristal no cuenta.', 'Del vacío, una ventaja: fundarse. Plantar bandera: la Iris.',
'Idea que se hacen de la Doris la Irma y la Cristal. Porque eso es la Doris.', 'La más bastarda de las bastardas: la Cristal. La Doris, la Irma, la Iris. Literatura de mujeres: en bastardillas.','Iris quiere decir ni en un lado ni en otro. Yo, Iris, naufrago. ','Hemos nacido de la Doris, de la Irma. Hemos nacido de un error.', 'Iris del mar que no hablas del todo ninguna lengua.', 'Y si se cruzan la Doris y la Irma en el corredor que da a lo de la Cristal, es la Doris la que retrocede, porque las dos no pasan.','Aunque señalemos con el dedo, en la espalda de la Irma hay pequeñas Irmas que disparan, desde adentro.','Hemos nacido de la Cristal, de la Iris. Hemos nacido de un error.', '¿Cómo se llamaba la Irma antes de que la Iris le diera el primer beso?', 'Ni la Cristal ni la Doris. La Irma.', 'Una novela sin nadie. En la que solo ellas están.', 'La Iris es ante todo una mujer de mar, y está acostumbrada a chapucear en mil lenguas sin lograr expresarse bien en ninguna.',
 
'La Iris te protege y la Iris te limita. Corresponde a la naturaleza de la Iris su propia caída. El hecho de que la Iris caiga es consecuencia de su estupidez. De la estupidez de la Irma, de la estupidez de la Doris, pero también de la Cristal.', 'Que la confusión reine por sueños como ese, que tuvo la Doris con la Irma y se besaban, la Cristal siempre tejiendo en otra habitación en su mente. La Iris no estaba.','Como la Cristal y la Doris, que de niñas pasaban su verano en la colonia, y ya no podrán pasar su verano en ninguna otra parte, nunca más.', 'No es ni la Irma ni la Doris lo que conduce a la locura, es el espacio entre ellas.',' 	Pasa un caballo marcado, se persigna la Doris.','Y si se cruzan la Iris y la Cristal en el corredor que da a lo de la Doris, es la Iris la que retrocede, porque las dos no pasan.','Se acuerda de la cinta de la Iris para curar el empacho. San Blas-San Blas. La Iris empieza a bostezar. Seguro estás ojeada. No hay mal que dure cien años. No hay mal que por bien no venga. Ya está.','La Irma habla y la interrumpe la Cristal. La Doris habla y la interrumpe la Irma.La Iris mira.','Habla la Doris, la Irma la interrumpe. La Cristal habla y la interrumpe la Iris.','Empieza con la narración de la vida de la madre de la Doris. La madre muere y la narración se corta. Y recién ahí se comienza a narrar sobre la Doris.', 'Pero es tal la evidencia de la Doris.',
'Entre ellas, jamás, que yo recuerde, se nombraban.', 'Lecturas que la Iris no hacía y que a las otras las salvaban.','La Irma no es sólo una mujer que se ha vuelto loca. Es una mujer a la que han vuelto loca.','La Cristal reducida a un montón de pequeñas imágenes despedazadas al borde de la línea que rodea sus ojos.', 'Y si se cruzan la Doris y la Irma en el corredor que da a lo de la Iris, es la Doris la que retrocede, porque las dos no pasan.', 'La Doris como un arma verbal y no como un sobrevuelo para futilizar el tema y para no involucrar política e ideológicamente a las otras. ','La Irma entiende menos eso de poner la otra mejilla que de la improbable existencia de un dios.', 'Yo no soy la Irma.', 'Terminan por descubrir que la verdadera poesía de nuestro tiempo anida no sólo en la Iris y en la Cristal, sino en la cotidiana, modosa Irma y en la anónima o mencionada mayoría de sus romances. ','Ni la Doris ni la Iris. La Irma.',

 
'Y cada detalle perdido es una Iris perdida, aunque quizás después de algún tiempo las Iris perdidas se convierten en algo sin importancia, como para permitirnos introducir un etcétera o dos.','La ridícula. La retórica. La desinteresada. La ridícula retórica desinteresada. La Irma.','La Doris es un tópico del que nos libramos por la Cristal. Es solamente en el país de la Cristal que una es la Irma.','Prueba evidente de que la Iris no se abre paso por sí misma.','Hace tiempo que la Irma siente muchas veces la tentación de quedarse en una actitud de indecisión.','Y si se cruzan la Iris y la Irma en el corredor que da a lo de la Cristal, es la Iris la que retrocede, porque las dos no pasan.', 'Ironía en que la Cristal no tiene nada que demostrar y tiene que jugar con las posibilidades mismas que socavan la demostración.', 'La Irma habla y la interrumpe la Doris.', 'La Iris y sus mapas, sus brújulas, sus banderas. La Iris y sus nudos.','Se trata de la Doris, no de la Irma. Muchas veces se puede dudar o discutir apasionadamente si una Doris determinada tiene buen sentido e imaginación y está libre de prejuicios; pero todos estarán de acuerdo en que la forma de ser de la Irma es valiosa y estimable.',
 
'Si por lo menos hubiera una Cristal ante quien protestar.','Días de ocio de la Doris. Borrones que las monjas escribían por encargo, con sueños o deseos pecaminosos, para ser censurados luego como biografías negativas.','La agudeza está en presentar la visión de la Iris sin que la Iris le haga perder la fuerza. No se nos invita a ver más allá de lo que ve la Iris, sino a ver con ella.','Por causa de especiales condiciones atmosféricas, la Cristal desaparece de vez en cuando: es así que si la Doris la ve venir, las asombra a las otras con una insólita fotografía de la Cristal viniendo.','La Iris tan luego, tan poco amiga de la Cristal.', 'En casa de la Irma, la Iris empieza el viaje del descubrimiento, hasta ahí el camino es conocido. Después, se guía por los semáforos, si está verde cruza y si no, dobla. La Doris dice la Iris va a donde la lleva el viento.', 'Lo que la Iris dice así sin más, no. También otra cosa.', 'Y si se cruzan la Doris y la Cristal en el corredor que da a lo de la Irma, es la Doris la que retrocede, porque las dos no pasan.', 'Ni la Iris ni la Cristal. La Irma. ','Ser la Cristal significa ser para la Irma y a través de la Irma para sí misma. La Cristal no dispone de un territorio definido sino que está, toda ella y siempre, sobre la frontera; mirando al fondo de sí misma la Cristal encuentra los ojos de la Irma o ve con los ojos de la Irma.', 'El que nunca vio ni conoció a la Iris, la Irma, la Cristal y la Doris no será culpado en juzgarlas por manchitas de tinta o pequeñas monstruo que forman travesuras.','Si hay en una casa alguna Doris natural o espuria luego se la despacha; si tiene alguna Doris dada la palabra de casamiento o ha causado perjuicio a alguna Iris y no quiere cumplir su obligación, huye. Esto sucede con todas las Doris por más órdenes que se les den. Y así se llena de Doris a quienes sólo mueve la avaricia, o la libertad de intentar vivir sin Iris, sin Cristal. La libertad de intentar vivir sin Irma.', 'De aquí han venido esos vocablos de Iris, Irma, Doris, Cristal; de que cada una tira para sí, cada una habla su lenguaje, no queriendo concertar con las otras.',
'La Iris puede sentirse, conózcanse o no las convenciones.', 'La Irma, la Iris: porque no tienen manos juegan una pulseada con la mente.', 'Doris a solas o con la Cristal. La Cristal a solas y con la Iris. Etc. ', 'Hemos nacido de la Irma, de la Iris. Hemos nacido de un error. ', 'Y ya ha pasado el tiempo en que la Iris contaba. ', 'Y si la Doris muere a los 75 años, es -en cada punto de su vida- una Doris muerta a los 75 años. ', 'Está imponiéndose en nuestros días una Iris crónica, que busca en todas partes la total suspensión de todo juicio moral, la artesanía verbal y virtudes semejantes. ','Y si se cruzan la Iris y la Irma en el corredor que da a lo de la Doris, es la Iris la que retrocede, porque las dos no pasan.', 'La sublime Irma despreciable. ', 'Ambivalencia de la Iris y de la Doris en el momento en que la Doris está cada vez más realista y la Iris se halla cada vez más penetrada por la Cristal y la Irma.', 'La Cristal va a ponerse en movimiento de un momento a otro con un destino conocido o desconocido para la Doris y la Irma que, asistiendo al espectáculo de su progresiva puesta en marcha, comienzan a imaginar, a temer o a esperar algún improbable incidente.','La Iris es ver con los ojos cerrados.', 'Y así es como la Irma se duerme pensando que sólo algo estrictamente literal podría romperle la cabeza.','La Doris traza el cuadrilátero aproximado fuera del cual se siente lejos de la Irma.','La Cristal piensa en instalar una flor de loto, sin regar sus plantas.', 'La Iris siempre gana.',

 	 
'Tenemos a la Doris dentro. De la Doris estamos hechos.',' La Iris, tan luego, tan poco amiga de la Doris. ','Y si se cruzan la Doris y la Cristal en el corredor que da a lo de la Iris, es la Doris la que retrocede, porque las dos no pasan.', 'En efecto, la Cristal se había perdido a lo lejos. Pero ellas seguían con la mirada fija en el punto donde había doblado y parecía que para siempre iba a faltar la Irma, que había dejado el mundo doblando en esa esquina.','¿De dónde sacaba la Cristal energías para soportar su espectáculo durante tanto tiempo? No hacía más que analizar lo que le ocurría, como si la suma de esos detalles fuera a darle la certeza de que vivía.',' Existe entre la Iris y la Irma una simpatía íntima, una relación común, que tuvo su origen en un comienzo en la defectuosa circulación de su sangre.','La cruel Doris que la realidad le había impuesto a su mundo.','Hoy debemos concebir a la Cristal no como Cristal, sino como Irma, Iris, Doris.','La Iris, la Cristal también enseñan cómo gobernar la lengua.','La historia de la Iris es un largo rodeo alrededor de la Irma. ','Algo como deben creer la Irma o la Cristal de las cosas de la Iris, de las cosas que no no pueden tocar.',

'Pasa un caballo marcado, se persigna la Irma.', 'Y si se cruzan la Iris y la Doris en el corredor que da a lo de la Cristal, es la Iris la que retrocede, porque las dos no pasan.', 'La culpa no es de la Irma, es de la Doris.', 'Como si ya no pudieran creer más en nadie de este mundo, como si las únicas en quienes confiar fueran la Doris, la Irma, la Cristal y la Iris, es decir, sólo aquellas que hubiesen pasado por su misma experiencia.', 'La que siempre gana es la Cristal.', 'Después pensó que la Iris era el miedo de que todo se perdiera y no conservara significado para nadie. ','No tener Irma, no tener Doris y querer conseguirse algo, una palabra con la que la llamen a una, que se la griten de lejos para que una vuelva, con la seguridad de que la necesitan o de que la reclaman. ','Una Irma que avanza longitudinalmente, como una onda que se propaga a lo largo de un muelle y una canción suena.',
'Y una Iris dispersa entre las Iris de otras que no me conocieron.', 'Ya nadie la recuerda con su nombre. Una extraña Cristal tan invariable y vasta.', 'Un día, te distraés y aparece la Olga.', 'Y si se cruzan la Doris y la Iris en el corredor que da a lo de la Irma, es la Doris la que retrocede, porque las dos no pasan.', 'La Doris, una materia amorfa, que se muere con la calma prudente de los objetos envenenados.', 'En cada Iris duermen Irmas y Doris olvidadas.', 'Si se enferma la Doris se enferma la Irma. Si se enferma la Irma, se enferma la Cristal. Si se enferma la Cristal, se enferma la Iris. La Doris no se enferma nunca.', 'Si se sale un punto en un tejido hecho por la Doris no es lo mismo que si se sale un punto en un tejido hecho por la Cristal.', 'Y si el nudo no se desata, quemarlo. Así es la Irma.', 'Dos libros: el uno que trata de todas las cosas que traen nuestras Doris y nuestras Iris, que sirven al uso de la medicina, y el otro que trata sobre la piedra bezoar hallada en el estómago de la Irma, que la Cristal conserva. ', 'Y que también la Iris, como la Irma, hubiera participado del nombre propio.', 'En el encuentro entre Cristales y Doris, interpretan que se llaman a sí mismas por las palabras que pronuncian.', 'Hallaron ciertas mujeres que, preguntadas cómo se llamaba una gran ciudad cerca, dijeron “Olga, Irma”, que vale “no te entiendo”. Pensaron las mujeres que se llamaba así y corrompiendo la palabra llamaron desde entonces “algo-ritma” u “olga-irtma”, y nunca se le caerá tal nombradía.', 'Porque las Irmas ardientes son apetecidas de todas las gentes.', 'La Iris crónica, progresiva, incurable.',
'Y si se cruzan la Iris y la Doris en el corredor que da a lo de la Irma, es la Iris la que retrocede, porque las dos no pasan.','Una Doris es una Cristal con una Iris y una Irma. ','Ir ajustando los patrones de normalidad a aquellos que la Doris impone.', 'El poder ficcional de la Cristal. ', 'El contorno atormentado de la Iris.', 'De todas esas Irmas y Doris que hemos nombrado, hay tanta abundancia que llegan a ser muy dañinas: han crecido tanto en algunos lugares que han vencido toda fuerza y voluntad humanas por desterrarlas, y han prevalecido de tal forma que han borrado los nombres antiguos de otras mujeres, forzándolas a que se llamen de su nombre, como a la Olga.', 'Como toda Cristal que habita en nuestro cuerpo.', 'La Iris era no tener frente al mundo ningún poder que hiciera daño.', 'Y la Irma le busca a la Cristal las lucecitas en los ojos.', 'Los lunares en la espalda de la Doris.','Tener una Cristal en el cuerpo es cargar con el peso de la Cristal.', 'Una simultaneidad fatal de Iris y Doris.', 'Se necesitan cuatro Irmas para producir cuatro Doris.','Nosotras mismas somos una especie de Irma.', '¿Y la última mirada de la Doris?', '	Y si se cruzan la Doris y la Iris en el corredor que da a lo de la Cristal, es la Doris la que retrocede, porque las dos no pasan.', 'La pregunta desesperada de la Iris, hija de padre desconocido, que pide a su madre muerta el secreto de su nombre.', 'No soportaba ya ese aire a la Cristal.', 'Era como si se hubiera dispuesto todo para un baile al que ni la Doris, ni la Irma, ni la Cristal, ni la Iris fueran a asistir nunca.',
'Desde las millones de Irmas que arden en el universo infinito hasta el centro preciso y misterioso de su conciencia.', 'Y me he detenido cuando, por la ventana del balcón entreabierto de la Doris, he adivinado, a través de los vidrios, la luz de la lámpara que alumbraba su reunión familiar.', 'El culto de la Irma, inventado por los literatos, aburridos de la literatura.  ', ' 	Como si pretendiesen interceptar a la Irma en función de la Cristal.', 'La pregunta desesperada de la hija de la Iris, de padre desconocido, que pide a su madre muda el secreto de su nombre.', '¿Qué es ser la Doris? Es salir de su casa, de su lugar, de su barrio, en busca de algo indefinible, inalcanzable, pues se confunde con la propia Doris.', 'A la Doris: en su lucha con los demonios la pobre Irma la convoca.', 'Y si se cruzan la Cristal y la Iris en el corredor que da a lo de la Irma, es la Cristal la que retrocede, porque las dos no pasan.', 'Y lo que no se puede esperar de la Doris es la propia Doris.', 'Una Iris que nadie reconoce. ', 'La Irma, la Iris, la Cristal y la Doris no son hijas de padre honrado. ', 'La Doris tiene en principio un carácter eminentemente técnico. Se aprende y se ejercita a partir del trabajo. Se diría que se ejercita trabajando sobre la resistencia de la propia Doris.', 'A toda la gran Irma que mereció su nombre.', 'Y todos los espejos en cuyos abismos se ha mirado la Irma', 'Y que no sepan más que la Cristal, sino que sepan con templanza.', 'Una Doris albina.', 'Todos los amantes de la Irma.','Una Doris pasa y dice "ay estoy tan contenta porque ahora en el baño hay un espejo y me puedo mirar". La Iris la escucha.', 'Para la Cristal, la Doris siempre va a estar en los lugares en que han andado juntas.', 'La Iris ha conquistado su propia vida.', '¿Tengo familia, tengo marido, descendencia en el mundo? No me acuerdo. La Irma vive en un paraíso sin consecuencias.',
  
 
'Y si se cruzan la Irma y la Doris en el corredor que da a lo de la Cristal, es la Irma la que retrocede, porque las dos no pasan.', 'La Cristal no representa, construye.', 'La Doris, complicada y perfecta ¿como el cerebro de quién? ', 'Hemos nacido de la Iris, de la Cristal. Hemos nacido de un error. ', 'La Iris inmensa por delante y no acercarse, la Iris toda abierta y no buscar nada. ', '¿Por qué no sentirá la Irma su belleza como siente sus dolores?  ', 'Solo que la Cristal anda más lento, mucho más lento que su ambición.', 'Siempre habrá más Iris por delante.', 'De modo que veremos a la Doris por todas partes y nada en la Cristal.', 'Cómo desviar el curso de la Doris.', 'O se está de más para la Irma o se está de más para la Cristal. Algunas cosas de la Iris mejor dejarlas así tal como ocurrieron en verdad, nunca narrarlas.', 'Sacala a la Estela, que todavía no está.', 'Como una Irma resucitando en sus zonas muertas.', 'La Cristal se acabó, pueden darle el tiro de gracia.', 'La Iris es despegar a la Irma de la Cristal. Y de las Irmas todas, de cuyas entrañas haya nacido el muerto.', 'La Doris es muy distinta a mediodía o a medianoche. Jamás dice lo mismo incluso usando las mismas palabras.', 'Todo lo que vive de la Cristal crece y se regocija.',

'El cuerpo entonces revienta por el empuje de plantas que crecen desde dentro, que abren sus brazos, sus piernas, sus dieciséis extremidades y hacen materia podrida de la piel que antes dibujaba el perfil de sus cuatro ombligos, de sus cuatro vulvas.', 'La saña de la Iris con la Irma.', 'Cuando la Doris dice quiero, la Cristal no quiero, la Irma es hora, y la Iris ahora  o nunca: se acabó lo que se daba.', 'Pienso en todas las Doris muertas. En todas las Doris quietas, como si se tratara de Doris congeladas, disecadas, embalsamadas. Quizás más embalsamadas que muertas. Exhibidas en un momento concreto de un acto. A punto de atacar. O enfrentaditas unas a otras como si estuvieran hablando, discutiendo. Todas las Doris como estatuas despedazadas, temblequeantes. Una Doris, otra Doris dura. Desmembrada.', 'La Doris, la Irma, la Cristal, la Iris, tienen la forma exacta, contraria de mi cuerpo.', 'Una Irma instantánea. Generada a partir de una imagen precipitada de sí.', 'La Doris la hace. No importa si cambia o en qué se transforme después.',
'La Iris tan luego, tan poco amiga de la Irma.', 'Pero es tal la evidencia de la Cristal.',
'La Doris no conoce la genuflexión.', 'La Irma es como un pájaro que nunca se posa.', 'La Cristal y la Iris se ponen de acuerdo o estallan, igual que las galaxias en el universo.', 'La letra de la Iris no es la misma escrita a medianoche o a mediodía. Nunca dice lo mismo, ni aunque forme las mismas palabras.', 'Y si se cruzan la Cristal y la Iris en el corredor que da a lo de la Doris, es la Cristal la que retrocede, porque las dos no pasan.', 'La Cristal es el enlace más débil entre la Irma y la Doris.','Y por no saber la Doris poner los nombres a esos dolores que siente, no los expresa.', 'La saña de la Irma con la Iris.', 'Idea que se hacen de la Irma la Cristal y la Doris. Porque eso es la Irma.',
'La Iris tan luego, tan poco amiga de la Doris.', 'La Cristal habla, la Cristal tiene el poder de hablar libremente.',  
'Se nubla de repente y se llena de alguaciles. ', 'Y si se cruzan la Irma y la Doris en el corredor que da a lo de la Iris, es la Irma la que retrocede, porque las dos no pasan.', 'La médica que firmó el acta de defunción de la Iris se llamaba la Irma.', 'Hay una baja de tensión, la luz se corta por un instante. Las cuatro miran al fotógrafo como si hubiera disparado un flash. La Iris mira, la Cristal sonríe: ¡whisky!', 'Una Cristal que oyó en el fondo del jardín habla en ella para decir.', 'Una Iris es una Irma con una Doris y una Cristal.', 'Por eso, hay que ir ajustando los patrones de normalidad a aquellos que la Iris impone.',
'La pobre Irma estaba desde niña contando los tumbos de su corazón y ya no le alcanzaban los números. Ya no puedo contar de ahora en más. Se rasca.','La Doris mira en el ropero la ropa: si no la usa se pone triste.', '¿Y por qué recurrir a la Doris, Iris tan atrevidas, a Irmas tan ingenuas para conseguir efectos de naturaleza estructural? No parece, sin embargo, que la relación muy asimétrica entre la Irma y la Iris, inaugurada por la Cristal, se haya modificado radical ni sistemáticamente.', 'Se levanta mal la Doris, la agarra a la Cristal. Que la intimidad con el otro mundo no es ningún peligro le quiere hacer creer.', 
'Se necesitaron tantas Irmas para producir tanta Doris.', 'De vez en cuando, muy de vez en cuando, dejan entrar a la Rita. La interrogan. Con sus diminutivos y sus cositas doradas. La mochi. El celu. El anillito transparente. Después le cuentan: sobre la orgía y sobre irse de viaje y volver con los ojos endurecidos. Dulzurita. Su nombre diminuto o diminutivo de qué. ¿Dónde está el óxido en las cositas doradas?', 'El día en que la arena tuvo la consistencia. Una mezcla perfecta de seca y mojada. Rugosa. Una masa que nunca volvieron a amasar. Se vino la tormenta y corrieron. Es un éxodo, decía la Edith, que sólo por esa tarde estaba con ellas. Pasó algo con una reposera. Se cerró antes de que la Irma llegara a sentarse. Se rieron.', 'La palabra irma no existía, entonces cuando se referían a ella la llamaban así, intercalando la palabra la Irma entre las palabras conocidas.', 'Y si se cruzan la Cristal y la Irma en el corredor que da a lo de la Iris, es la Cristal la que retrocede, porque las dos no pasan.', 'Una no es de ninguna parte hasta que no tiene una Iris muerta bajo la tierra.', 'A la Irma lo que se le cuestiona es la posición. A la Iris, la conducta.', 'Los helechos y las begonias (el corredor de las).', 'La saña de la Cristal con la Irma.', 'Y cuando se amontonan, forman una masa irregular, con ocho brazos, tres úteros, cuatro corazones.', 'Corta una tira larga de papel. Dobla el papel como si fuera un acordeón para formar un cuadro. Dibuja el contorno de una persona en el medio del cuadro. Corta el dibujo. Desdobla lentamente el papel. Una tira larga de Iris tomadas de la mano. O de Irmas. Nunca de Cristal.', 'La distancia entre una y la otra soluciona en parte la simultaneidad de sus tiempos. Cuando están muy cerca, si habla una, la voz de la otra puede superponérsele. Y se ha dado el caso de que la Iris dijera “desierto” porque la Irma quería decir “deseo” o la Doris “cierto”.','Pero saben que el tiempo es siempre tiempo y el lugar es siempre y sólo lugar: no ralean lo real ni cometen ninguna falta, fatales reinas, sirenas de lo que hay. Y de lo que no hay.', 
'Véanse si no esas figuraciones que harían las veces de personajes. O esas figuritas. Restos tranformados de las Iris y de las Irmas de otras épocas.', '¿Cómo sería la Doris con una familia?', 'Ellas cuentan una historia de incesto, parricidio, fagocitación. Pero no pasa nada, porque no hay nadie.', 'Y si se cruzan la Irma y la Cristal en el corredor que da a lo de la Doris, es la Irma la que retrocede, porque las dos no pasan. ',
'La Doris cansa. Empieza con el no avisaste y las reclamaciones. No avisaste el sorteo en la panadería. No avisaste el color de la campera. No avisaste el Miguel que venía. No avisaste la comida que te mandaste. No avisaste que ibas de la Irma. No avisás. Te guardás todo. Siempre la misma cantinela. La Doris cansa.', '¿Es o se hace la Irma esa?', 
'Nunca veremos a la Cristal por todas partes y nada de la Iris.', 'Imposible desviar el curso de la Iris.', 'La Iris, la Cristal aparecían incluso antes de ser llamadas, incluso antes de que alguien más las concibiera, y siempre llegaban mucho más lejos de donde nadie se hubiera atrevido a verlas llegar. ', 'La Doris cuenta un sueño y pone empeño en los detalles, se esfuerza en no mentir. Esfuerzo que es bastante menor en la vigilia. O en la realidad. O en la ficción.', 'La Iris gira y gira, quiere morderse un rabo que no existe.', '¿Alguna vez la Doris, la Cristal se han vuelto intercambiables? Se han vuelto sobre sí, qué novedad.', 'Por vos la Iris me desprendo ahora de todas mis mejores palabras, que han sido para mí como una casa. Y de aquí en adelante serás llamada en mi lugar la Iris, la tantas veces grande, la que no dice la palabra a tiempo, pero acerca el gesto, toma del brazo a monstruos asustados, no teme a sus palabras desencadenadas, no tiene aliados, pero canta, y cuando está por llegar el que ya siempre ha llegado, canta. Abraza y baila: quizás en las palabras que no dice encuentre una violencia tranquila, un arrebato, algo del mundo a su favor.  Quizás: algo del mundo.', 'En el lugar exacto de la Irma.', 'Y así es como la Iris, la Doris, se enfrentan a sus padres: sin conocerlos.', 'La saña de la Doris con la Irma.', 'La gracia divina, es decir la Cristal, no la alcanza cualquiera así, por sí sola.', 'Y si se cruzan la Cristal y la Irma en el corredor que da a lo de la Doris, es la Cristal la que retrocede, porque las dos no pasan.', 'Si la Cristal se muere a los 85 años, es -en cada punto de su vida- una Cristal que muere a los 85 años. ', 'La Cristal tan luego, tan poco amiga de la Iris.', 'Cuando la Doris mira directamente a la Cristal, los rayos de luz de la Cristal se enfocan en sus ojos: una mancha amarilla ovalada en el centro de la retina, responsable de la visión central detallada y aguda (también llamada “agudeza visual”). Que la Doris mire continuamente a la Cristal hace que esta desaparezca. Su agudeza visual produce un dolor agudo y prolongado en la parte del cuerpo que mire de ella. Lo mismo ocurre cuando la Irma mira a la Iris, porque hay algunas que no resisten ser miradas directamente la una por la otra.', 'El caso es que la previsión que podamos tener de la Iris es inmensamente incierta.',
'Una Cristal no puede pensar dos veces en una misma Iris. He aquí que la simulación, la habilidad de mostrarse otras, se les presenta como una facultad de mujeres sanas, mujeres normales, casi como un estilo, una necesidad.', 'La Irma a la Cristal no la suelta, con todas sus complicaciones. Una Irma sin una Cristal se encuentra siempre en mala compañía.', 'La Irma para la Cristal es tan peligrosa como el agua para quien está a punto de ahogarse.', 'El problema es si la Irma empieza a recortar la realidad y, según esos recortes, a ponerles nombres.',
'Lo que la Irma dice así sin más, no. También otra cosa.', 'Todo lo que creías que era la Iris va a desaparecer. Una nunca termina de conocerse a sí misma.', 'La Irma: el riesgo que corre, el riesgo que representa.', 'Una sola actriz, para representarlas a todas en una jornada solemne.', 'Ambiciosa y llena de esperanza, la Irma que debiendo rasguñar apenas su supervivencia, tiende a ubicarse siempre un poco más allá de sí misma.', 'La tristeza de la Iris se reactualiza en un nivel lógico más elevado.', 'La Irma es el enlace más débil entre la Doris y la Iris.', 'El cuerpo de la Doris lleno de fuego: hay viento, la enfermedad se expande.', 'Aceptar la Cristal en mí, con todo lo bueno y con todo lo malo, ser unidad en ella y con mis frases claras y oscuras para empezar a ver.',
'Y si se cruzan la Irma y la Cristal en el corredor que da a lo de la Iris, es la Irma la que retrocede, porque las dos no pasan.', 'Se tenía cólera a sí misma por haberse dejado seducir por las aventuras de la Iris.', 'No hay dios. La Iris, la Doris, la Cristal y la Irma se sostienen por sí mismas.', 'La Cristal tan luego, tan poco amiga de la Irma.', 'Por qué diablos la cara de la Doris la mira así, es de echarse a llorar.', 'Que la Iris atravesara la palabra la Iris que casi siempre gana la partida y puede con todas, la Iris absorbe feroz, implacable, como un maelstrom, la Iris se traga todas las Doris, todas las Irmas, todas las Cristales del mundo, para volverse Iris, solo Iris, frase, sonido seco, cáscara del mundo, Iris suelta, sin Cristal.', 'La antinomia entre la Cristal y la Iris tiene su origen en la elección del nombre.', 'Y se ha dado el caso de que la Doris dijera “persevera” porque la Irma quería decir “severa” o la Cristal “perversa”', 'Porque lo que vale de la Cristal es su posición junto a la Irma. O frente a la Cristal. O mejor: entre la Cristal y la Doris.', 'Como si la visión directa orientara mal a la Irma.', '¿Cómo vamos a usar la misma lengua para nombrar a la Doris y al relámpago?', 'Cuando están cerca, pueden ver el detalle alucinado de sus caras, cerca. Todo ahí, al ras.', 'Dicen que la fermentación del propio cuerpo de la Irma es lo que la alucina. Un escándalo.', 
'Irse al culo del mundo no quiere decir irse de la Cristal.', 'Una Cristal es una Iris con una Irma y una Doris.', 'Y se ha dado el caso en que la Irma dijera “algo sucede” porque la Iris quería decir “un sauce” o la Cristal “seduce”.', 'La Doris usa todo lo que encuentra en su camino para propagarse.', 'Y los rasgos firmes de la cristal no fueron, en un principio, sino movimientos, que al realizarse repetidamente terminaron por adquirir un ritmo, volverse habituales, casi como una huella, permanentes.', 'No hay Irma bien encaminada que no desemboque en una Iris.', 'Porque la Iris hace lo que quiere, no lo que la costumbre quiere que haga.', 'Pero a la Cristal toda palabra ajena la desacomoda, como si penetraran primero y espolvorearan luego sus astillas dulces de cristal molido.', 'Crece la Doris terrible y alegre, crece su silencio, y en sus límites, da lugar, deja que se aparezca la voz de la Cristal, que habla siempre bajo las formas de la crueldad.', 
'Si la Iris se muere a los 95 años, es -en cada punto de su vida- una Iris que muere a los 95 años.', 
'Y si se cruzan la Cristal y la Doris en el corredor que da a lo de la Iris, es la Cristal la que retrocede, porque las dos no pasan.', 'La Cristal tan luego, tan poco amiga de la Doris.', 'Y ellas qué saben: si partiendo de un punto común cabalgaran en dirección de los cuatro puntos cardinales, se desmembrarían.', 'Está la Doris entidad producida exclusivamente en el lenguaje, como una arruga, un grumo, una excrecencia en el discurso de alguien –y está la que cuando se escribe se borra del mundo. Y está el lugar donde el paisaje y las arrugas de la Irma, la Iris, la Cristal y la Doris se confunden.', 'El miedo de la Irma no es más que la conciencia de la Doris que corre a otra velocidad.', 'La forma de la Irma no es más que su carga monstruosa, libidinal.', 'La Iris, la Doris confunden la luz de la Cristal con luz de luna y se enamoran, y buscan a la Cristal, anhelan aparearse, pero ¿qué encuentran? muerte.', 'La necesidad de que el himen de la Iris sea atravesado es histórica; la de encontrar palabras para decir y cómo combinarlas también.',
'¿Qué es la Cristal sino la negación del cuerpo de la Iris?', 'Las gotas de la leche de la virgen. Las gotas de la leche de la Iris. Leche de nubes.', 'A medida que aumenta la superficie de la Doris, aumenta su libertad. La superficie que ocupa no le impone a su ser ninguna limitación, ninguna estructura, como hace la Iris.', 'Lo que la Cristal dice así sin más, no. También otra cosa.', 'Y si se cruzan la Irma y la Iris en el corredor que da a lo de la Doris, es la Irma la que retrocede, porque las dos no pasan.', 'Porque las mujeres que transmutan se disuelven, dan lugar a la permutación y no a la instrospección.', '¿Cómo sería la Iris con una familia?', 'La Cristal y la Doris aprendían de memoria canciones que duraban bastantes años, y en ese tiempo adquirían el hábito de no decir, sino de cantar y de ser discretas.', 'La Iris corta las palabras y también las emociones, no dice decaída, dice deca, no dice angustiada,, dice angus. Y cuando está angustiada es porque no les sigue el ritmo a las palabras de las otras.', 'La Irma es tan horrible que es bella.',
 
 
'Cuando una Iris comete un error, automáticamente las demás se enteran. Incluso las del futuro. Eso quiere decir que la capacidad de las demás es mayor que la capacidad de la Iris para seguirse el ritmo.' , 'Pero la línea entre la vida de la Doris y la vida de la Cristal es cada vez más lábil.', 'A veces encuentran patrones entre ellas, que no deberían estar ahí.', 'La Iris es el enlace más débil entre la Cristal y la Irma.', 'La Irma tan luego, tan poco amiga de la Iris.', '¿Puede ser que la Cristal esté soñando con ella misma?', 'Cuando la Irma murió repetía unas palabras, decía ‘ay dios mío, ay dios mío’, y lo decía con una desesperación sin fuerza.', 'La médica que firmó el acta de defunción de la Irma se llamaba la Doris.', 'Pero es tal la evidencia de la Irma.', 'Entonces la Iris está en un lugar y la Cristal en otro. Las aguas se mueven en todas direcciones. Por momentos, la disociación que experimentan revela voces, visiones y deseos no armonizados en su interior. Esa confusión orgánica que las habita influencia sus movimientos. Van sin foco, sin diana hacia la cual apuntar su flecha, presas de distracciones que las agotan y las confunden.', 'Porque ser tu propia Doris será el desafío del futuro.',
  
 
'A la Irma le cuesta ponerse en la ecuación.', 'A veces se divierten. Después, la Cristal duerme la siesta, como flotando.', 'La Cristal agradece que haya un sitio, aquí, donde ya no siente dolor. Tratar de definir ese espacio de ellas, desde el que hablan, y que a veces toma forma, lentamente, pero es una forma muy precaria y muy incierta, y no creen que vaya a tener otra forma, aún.', 'La saña de la Irma con la Cristal.', 'La Iris, La Irma, la Cristal, la Doris repetidas, reiteradas, no conforman ningún personaje, ninguna presencia, ninguna abstracción de una característica gramatical.', 'El flash se ha disparado infinidad de veces y ha formado una sala de vidrios espejados. Y esos espejos son los espejos de ellas aunque no estén allí, aunque no sepan reflejarse ni estar presentes.', '¿Cómo es posible que la Doris, la Cristal sean capaces de sentarse a la mesa en esa sala de vidrios espejados, de inventar un salón de baile, de usar sus vestidos y bailar, beber más que sus brebajes digestivos, después de todo lo que han vivido, casi como si nada hubiera en verdad cambiado?', '¿Y a qué distancia está la Irma de las que ya no están?', 
'Y es nombrada por su nombre como por un rayo que no alcanza a matarla.', 'Cómo desviar el curso de la Cristal.', 'Por eso, no estaría mal ir ajustando los patrones de normalidad a aquellos que la Irma impone.', 'Situación entre dos de ellas –generalmente la Irma y la Cristal. Se miran una a la otra y esperan cada una que la otra diga hacer algo que las dos desean, pero ninguna de las dos está verdaderamente dispuesta. Así cada una está esperando que la otra se decida a hacer algo que sólo sería posible hacer las dos. No dicen nada.','Y si se cruzan la Cristal y la Doris en el corredor que da a lo de la Irma, es la Cristal la que retrocede, porque las dos no pasan.', 'Y si se ausculta el corazón de una se oyen los corazones de las otras.', 'Cada Irma posee su propio modo de calcular la distancia óptima que la separa del cuerpo de la Doris, de la Cristal, de la Iris. Y en función de esa distancia modula la voz y las demás deben respetarla.', 'La Doris se deja estar un poco y las come la mugre.', 'No tienen cuerpo, pero la basura se les amontona.',
'Y si no hay, no comen. Porque no tienen, porque no les alcanza.', 'Y si vuelven una a la otra es porque mal que mal…', 'Idea que se hacen de la Cristal la Doris y la Iris. Porque eso es la Cristal.', 'El de la Iris es un lenguaje sin voz, la manifestación impersonal de algo que habla.', '¿Y si no tienen cuerpo, pero tienen hambre?', 'La médica que firmó el acta de defunción de la Cristal se llamaba Iris.', 'No soportaba ya ese aire a la Irma.', '¿Cómo sería la Cristal con una familia?', 'Entre los elementos repartidos entre las amigas de la Doris cuando la encerraron, figuraban: varios objetos de plata, una sortija de oro esmaltado con un diamante, un crucifijo con su pedestal, sillas, un baúl antiguo, dos juegos de sábanas de seda, tinajas de aceitunas, una cruz grande y negra, varias botellas de vino, un escritorio de madera, apuntes, cinco canarios con sus jaulas, un frasco de mermelada con flores de papaver nudicaule, un diario. La Irma no quiso conservar nada excepto las fotos; incluso las paredes de su habitación fueran derrumbadas unas pocas semanas después de su encierro, y quemados el resto de sus elementos.', 'La Irma tan luego, tan poco amiga de la Doris.','La Irma se presenta enigmática en sí, primero en la excitación de sus nervios, luego en las características de su imagen y, por último, y sólo por último, en tanto griterío articulado.', 'Si la Irma se muere a los 65 años, es -en cada punto de su vida- una Irma que muere a los 65 años.', 'Pero es tal la evidencia de la Cristal.', 'Y si no hablamos del país de Jauja, tampoco hablamos por ningún motivo de la esencia de la Iris.', 'Si alguien esconde a la Cristal detrás de una pared, luego la busca en el lugar que la dejó, y sucede que la encuentra, en ese hallazgo no hay gran cosa a destacar, y sin embargo, eso es lo que sucede cada vez que alguien se encuentra a la Cristal, y al encontrarla hay algo cierto: ingresa en su jurisdicción.', 'Y si se cruzan la Irma y la Iris en el corredor que da a lo de la Cristal, es la Irma la que retrocede, porque las dos no pasan.', 
'Muchas veces piensa que no se ha salteado nada, que no pasado nada por alto, pero hay resquicios en la trama que las vuelve indefinidas e incomprensibles.', 'En efecto, existe algo más tenaz que la Doris: la Cristal.', 'La Irma y sus procedimientos que carecen por completo de alguna sutileza.', ' Uno de los principios fundamentales de la Iris –como de la Cristal– es la nitidez. La Iris, La Cristal, a no ser que sean manipuladas a una rapidez extrema y en una misma dirección y no en ambas, producen la desgarradura, el borde irregular.', 'Lo que la Doris dice así sin más, no. También otra cosa.', '¿Pretendería acaso hacer caber una Cristal dentro de otra?', 'La Iris, la Irma, la Cristal tienen la misma forma de estar quietas.', 'Ellas no son la materialización del deseo de nadie que las haya convocado en sus recuerdos, son como restos que poco significan.', 'La Doris no tiene tiempo de hacerse lugar en las palabras.', 'La Irma tan luego, tan poco amiga de la Cristal.', ' Sólo entre ellas se sostienen la mirada. Una mirada que empezó en el comienzo de los tiempos y se sostiene aún. Aunque quizás con algunos puntos ciegos. Que no sabremos nunca si en común.', 'La Doris no tiene tiempo de constituirse en el habla.', 'La Doris abre la puerta y la sostiene: pasa la Cristal. La Cristal la sostiene: pasa la Iris.', 'No es que necesite a la Doris, sino el lugar que la Doris le daba.', 'La Cristal es, como el gris, su propia complementaria.',
'Una libreta negra, chiquita en que la Irma anota los números que va jugando a la quiniela. Los que salen. Lo que gana y lo que pierde.', 'La saña de la Irma con la Cristal.', 'Pero es tal la evidencia de la Iris.', 'Puede ser que la Liliana aparezca también, en algún momento.', 'Yo no soy la Iris.', 'La Doris tan luego, tan poco amiga de la Iris.', 'Y así es como no debe estimarse más a la Cristal que a la Doris, puesto que la Doris depende de la Cristal y no todo lo que depende de algo es menos noble que aquello de lo que depende.', 'El problema es la Irma, que subordina el conjunto de sus referencias a lo que dicen la Cristal y la Iris, que no siempre acuerdan.', 'En ese sentido es que no estaría mal ir ajustando los patrones de normalidad a aquellos que la Cristal impone.', 'La Doris puede sentirse, conózcanse o no las convenciones.', 'Y así la Doris, la Cristal y la Iris se invitan a cenar, se abrazan, se retroalimentan. Ninguna de las tres es más importante que la otra, porque lo cierto es que ninguna vive sin las otras. Y a veces se encabritan y va una en detrimento de las demás, por cosas más grandes que ellas, o porque no pueden tomar el mismo rumbo. Pero cuando se encuentran frente a esa situación respiran y cuentan hasta tres, parece que están de pie de nuevo y entonces aparece la Irma, que había quedado afuera y multiplica un malestar infinito.', 'La poca consistencia de la Irma hace pensar que su fatalidad es ser una especie de dependienta, una mujer sobresaliente, pero adosada a otra mujer mayor, de infeliz trascendencia.',
'Por eso la Irma nunca avanza, o su avance es más periférico, satelital, que hacia adelante.', 'La Doris es el enlace más débil entre la Iris y la Cristal.', 'La Doris tan luego, tan poco amiga de la Cristal.', 'Idea que se hacen de la Iris la Irma y la Cristal. Porque eso es la Iris.', 'Pasa un caballo marcado, la Cristal se persigna.', 'La Irma dibuja unos pájaros perezosos.', '¿Cómo sería la Irma con una familia?', 'La Cristal puede sentirse, conózcanse o no las convenciones.', ' No es posible intercalar ninguna Olga arbitrariamente pues cada Doris difiere apenas en un grado infinitamente pequeño de una Cristal.', 'Ni la Cristal ni la Doris. La Irma.', 'Y aunque quisieran no podrían escapar de sí mismas, de toda esa trabazón que las vincula.', 'Y sólo con dibujar una silueta alguna de ellas se manifiesta. Es la potencia de los bordes en una tierra sin metáforas.', 'La Doris pide que le desenreden la maraña de lanas. Hay de todos colores. Son los días en que ya está internada. La Irma se le sienta al lado y se las desenreda. La lleva más de sesenta días. Antes de morirse, la Doris dice: ¿Qué mierda querés que haga con todo esto?', 'La médica que firmó el acta de defunción de la Doris se llamaba la Cristal.', 'Una Doris podría ser descompuesta en partecitas cada vez más pequeñas, hasta el infinito, y cada una de esas partes en partes aún más pequeñas, y aún en su expresión más elemental aparecería la Cristal.', 'Y si se cruzan la Iris y la Irma en el corredor que da a lo de la Doris, es la Irma la que retrocede, porque las dos no pasan.', 'Por ejemplo si a una Iris se le enseña un caballo marcado, recuerda el dolor que le ha causado y se persigna.', 'Se miran una a la otra como diciendo qué ganas de hablar con quién', 'Aquella relación necesaria entre el dolor de la Irma y el instrumento que lo ha provocado. ', 'Cuando esperamos que mañana habrá una nueva Cristal, actuamos empíricamente, porque esto ha sido siempre así de ese modo. Pero no esperaríamos otra cristal si no actuáramos, además, con ternura.',
'Tanta Iris como sea posible.', 'En la inercia natural de la Doris.', 'Y el cuerpo de la Cristal como un espejo en el que se refleja todo lo que ocurre en la vida de la Doris.', 'En las letras de su nombre tiene la Iris escrito su propio futuro.', 'Por donde se mire, encontraremos a la Irma, inclusive en las partes ínfimas, diminutas de la materia.', 'Cada Irma, cada Doris puede pensarse como una selva poblada de lianas o como un pantano repleto de barro o como un abrojal lleno de abrojos tajantes, pero cada liana, cada porción de barro, cada filo del abrojal podrán pensarse a su vez como selva, pantano o abrojal de Irma, de Doris, y hasta de Cristal.', 'Prueba evidente de que la Cristal no se abre paso por sí misma.', 'No soportaba ya ese aire a la Doris.', 'Y aunque la Irma, la Doris que existen entre las lianas, entre las porciones de barro, entre los abrojos, no son ni Irma ni Doris, contienen sin embargo otras Irmas y otras Doris, cuya simplicidad es tal que apenas podemos percibirlas.', 'Ninguna Iris se percibe a sí misma como un resorte arriba y abajo en la jerarquía del lenguaje cuando sencillamente habla de las cosas con las que se va encontrando.', 'En el relato de la Cristal, la Doris debe permanecer pasiva.', 'La Irma, la Iris pueden ser muy reacias a comportarse como realidad de una forma que resulte medianamente satisfactoria.', 'Y así veremos a la Irma en todas partes y nada de la Doris.', 
'No hay nada maravilloso en poner a la Irma, la Iris, la Cristal y la Doris como figuritas abstractas, alejadas de sus animales y de sus nubecitas. Del crecimiento de su pelo y de sus uñas. De su rabia.', 'Es innegable que comparten ciertas características, pero no es posible afirmar que tengan la misma forma, dado que son como huecos, han nacido de forma negativa, como restos descartados de algo confeccionado positivamente y con posterioridad.', 'En el fondo de la Irma está la Iris. El límite entre ellas es el doble filo de una espada.', 'Pero veremos a la Iris en todas partes y nada de la Irma.', 'Empecinamiento de la Iris por estar ahí.', 'A veces parpadeaban las cuatro al mismo tiempo.', 'La Doris dice algo, le habla a la Cristal, pero la Cristal no la oye. Y aunque no la oye, decide no preguntar. ¿Qué pasa si no escucha? Es la primera vez que decide no preguntar. Después la sensación de haberse perdido algo, ella que siempre está en todo, que va palabra por palabra, algo que ya no va a poder recuperar.', 'Después la escucha a la Doris hablar con la Irma. ¿No pregunta? dice la Irma. No, nada pregunta. Pero algún día algo le vas a tener que decir. La Cristal se encierra de nuevo. No pregunta.', 'Estar en el mundo de la Iris, en el mundo de la Cristal. Oponer resistencia a ambas a la vez.',
'El de la Cristal es el arte de dividirse, que es por definición también el arte de multiplicarse.', 'A veces, la voz de la Doris parece venir directamente de su cerebro y no de su garganta.', 'Como si una de ellas se hubiera arrojado a tomar la sortija en la calesita que las sostenía y ya no pudiera volver.', 'La Irma deja a la mitad una frase, la Iris dice: “pasó un ángel”.', 'Son mujeres que huyen, pero no van, parece, a ninguna parte. Huyen, se fugan como el ánimo se les fuga ante sí mismas cada mediodía.', 'Algo decepcionante cuando comprenden que las letras en matemática están en lugar de números y que nunca aprenderán a sumar verdaderamente X e Y como lo harían si tuvieran valores absolutos.', 'Pasa un caballo marcado, se persigna la Iris.', 'La Irma puede sentirse, conózcanse o no las convenciones.', 'Es lo que la Cristal podría haber sido de no haber estado expuesta a la vida, es el reflejo de una serie de posibilidades, a las que en verdad les falta todo lo que se refiere a la actualización específica de esas posibilidades.', 'A veces la Doris confunde el dolor con el instrumento que le causó dolor. O confunde el instrumento que le causó el dolor, con la materia con que ese dolor trabaja.', 'La Iris anota: la extraño a la Estela. Nunca la conoció.',
'Sólo es posible semejante Irma si se toma la distancia necesaria como para hacer entrar en el campo visual las líneas que la definen.', 'La Iris cuando habla dice cada frase como si fuera la última, como si cada palabra que pronuncia le salvara a cada paso el pellejo, como si no dijera nada sino al borde de algo, de un desbarrancadero quizás, de un abismo. La Doris, en cambio, habla por hablar.', 'La Cristal grave y reservada, conoce de memoria la tierra que va de su casa a la de la Irma, y si quisiera podría andar veinte mil leguas cuadradas de llanuras, de bosques, de montañas. Su pasión es el movimiento. Reservada y modesta, sabe todos los secretos de la Doris, de la Iris, y como de esos secretos depende la vida de ellas, la Cristal los cuida, se los lleva consigo si se va, y los pone a salvo ni bien desensilla cuando llega.', 'Prueba evidente de que la Doris no se abre paso por sí misma.',
'Yo no soy la Cristal.', 'Y la malvada Irma, perseguida por la justicia desde hace tiempo. Su nombre es temido, se lo pronuncia sólo en murmullo, sin odio, pero con respeto. Es una mujer misteriosa que no tiene una morada fija, les roba palabras a las otras, se queda con lo que quiere y lo demás lo transforma, hace lo que quiere con eso, porque esa es su profesión, su ciencia. Mala como la peste, dice la Cristal.', 'Pasa un caballo marcado, la Cristal se hace la señal de la cruz.', 'La Iris y el rayo que no la mató.', 'La Cristal, la que empuja hacia adelante siempre.', 'La Irma como una cadena que se suelta y a su paso arrastra cuanta cosa se le ponga en medio.', 'Sabe la Iris que los números que la Irma anota en la libretita negra son presos de una contingencia que podría simular el azar, pero sabe también que bajo el azar se desplaza la melodía boba de la necesidad misteriosa, como una causa que todo lo puede, incalculable e intratable, pero necesaria en cada trazo para el sostén de su historia.', 'Un pasado en que la Doris no se llamaba por su nombre sino por el nombre de lo que perseguía, es decir, la Cristal. Ahora su nombre le pertenece, aunque no tanto como para afirmar que le pertenezca por completo.', 'Prueba evidente de que la Irma se abre paso por sí misma. Cómo desviar su curso.', 'Y de las cuatro que había llegaron a tal extremo que se comieron las unas a las otras, hasta que quedó una sola, que por ser sola no hubo quien se la comiese.', 'Y cuando recién la conoció, “ahí” era el término que usaba para referirse a la Cristal, a quien nunca nombraba.', 
'A veces suena una sirena a lo lejos y se miran una a la otra como para saber quién es quién.', 'Hay una fila de Irmas, Iris, Cristales y Doris, son varias, una al lado de la otra. Pueden estar en tres estados: alegre, triste, indiferente. Representamos esta situación como una lista que en cada posición tiene un 0 (alegre), un 1 (triste) y un -1 (indiferente). La tristeza se propaga de forma inmediata de una a la otra, de cualquier Irma, Iris, Cristal o Doris triste a cualquier Irma, Iris, Cristal o Doris indiferente que tenga a su lado. Si está alegre no se contagia.', 'Y ellas celebran su cualidad de ser blandas. Cualquier cosa que se les presente como amenaza la integran y se la van pasando de mano en mano. Quema un poco al comienzo, pero enseguida queda neutralizada su quemazón. Y no por eso pierden valor, sino que lo constituyen en una masa informe de significados iguales, y cada una vale por su capacidad de ser cambiada por la otra, en cualquier posición del sistema, sin alterar por eso en demasía el sentido.', 'La cara de la Iris se borra y se dibuja la sonrisa de quien ha impuesto su delirio. La Irma dice: su cara se fue.', 'Entonces se sientan a la mesa y estallan a carcajadas. Les genera una felicidad gozosa intercambiar sus nombres. Doris le dice “Irma” a la Cristal. La Cristal dice “Doris” y no sabe a quién se dirige. La Iris se repliega a un costado, espantada. Y así y todo siguen equivalentes, porque decir “la Doris” significa ella y la otra a la vez. Y es que lo mismo ocurre con decir “la Iris”. ', 'Yo no soy la Doris.', 
'Para la Iris, “salida” no significa “salida” sino salida de la Irma.', 'Y en ese preciso instante ficticio de su existencia ficticia, la Cristal dice basta.', 'La más Iris de entre las Iris puede transmitir el resumen de esos momentos a los que efectivamente se aferró.', 'No soportaba ya ese aire a la Iris.', 'Parecen vaciarse de sentido, sí, olvidar su pasado, como si se nos presentaran en un proceso inevitable de aplanamiento e indiferenciación, gobernadas por la lógica del parecido, de la reduplicación, como un boceto perfilado apenas. Y sin embargo, siguen caminando obstinadas, encontrándose en la vereda una a la otra, señalando la bandada de alguaciles cuando se acerca, marcadas por el tedio, y sobre todo por el desamparo.', 'La Iris no puede controlar ninguna historia que cuenta.', 'Pero es tal la evidencia de la Irma.', 'Es el cumpleaños de la Irma. La Cristal hace una torta de algarroba y frutillas. A las doce, le cantan el feliz cumpleaños. La Irma desea: ojalá, ojalá, ojalá. La Doris le regala la manga para decorar. La Irma se queda un rato largo mirando la nada. Piensa en la Iris. ¿Te fuiste a otro cumpleaños? Pregunta la Cristal.', 'La Doris tan luego, tan poco amiga de la Irma.', 'Cuando están juntas nada se anticipa, todo llega y se instala de pronto. Tienen la mente libre de obsesiones mágicas, nada las acecha, sólo se entregan a lo que sucede entre ellas.', 'La Irma como el espacio para desviarse interiormente.', 'La Iris conoce a la Cristal principalmente por la forma en que su nombre se la presenta. Y la Cristal traza un círculo mágico en torno de la Iris que la conoce, un círculo del que es imposible escapar, a no ser que se penetre en otro.', 'Aquella Irma particular en que la Iris comienza a disolverse.', 'Y cuando le piden que cuente una historia, la Cristal no cuenta. Una historia necesita un faro. La Cristal no tiene. La pequeña casa al borde de su casa, la pequeña escalera al pie de la escalera, el horno micro-ondas que sólo piensa en sí. No entiende el fuego. Y tiene un mar conchudo: no se deja. Está siempre de rompiente en la orilla. Y esa arena que no termina de despegarse nunca…  Como si se le hiciera mineral en sí.', 'Una Iris albina.', 'Entre todos los amantes de la Irma.',
'Y una vez constituido ese espacio ajeno a la Cristal, ya no puede abrirse a la Cristal en ninguna parte.', 'Totalidad de un mundo resumida en la mirada retrospectiva de la Iris.', 'Entonces la Cristal ha perdido su cualidad de ser para convertirse en sólo dos sílabas.', 'Lo único que no hay que hacer es buscar más allá de la Iris, la Irma, la Cristal y la Doris. Ellas mismas son la Iris, la Irma, la Cristal, la Doris.', 'A veces se miran al espejo y dicen: hemos sido tomadas por cierto horror intransferible.', 'Hacer volver a la Iris, a la Irma, la Cristal y la Doris a aquellos lugares que ocuparon cuando se las necesitó.', 'Están por entrar a natación. La Doris dice “la Cristal derramó café en la pared esta mañana”. Las demás ven la mancha. Se ríen. La Cristal habla con la Mimí, que un poco la enamora. Y de lejos se escucha la voz de la Doris “La Cristal se está tomando un café en las nubes”. Y a partir de allí esas paalbras aaprecerán siempre juntas. La Cristal derramó café en la pared esta mañana. La Cristal se está tomando un café en las nubes.', 'La Iris recorre la ciudad de manera exhaustiva, no le queda una sola cuadra por conocer. La Doris, en cambio, descubre a último momento que si cruza un puente se encuentra otra ciudad hermanada, por ella nunca conocida, que le va a quedar sin recorrer.', 'La potencia de la Iris, su desafección, algo de ella persiste en la intemperie.', 'Están cansadas. A veces dejan de responder, y lo cierto es que no saben articular ninguna palabra que se salga de ellas para ir a alguien más, no saben llamarse sino entre ellas, y a veces ni siquiera, sólo responden, y hasta hay momentos en que ninguna de ellas responde en sus mundos. Es cuando se lo traga todo el ruido del mar.', 'Y en el ámbito de la Iris, de la Irma, de la Cristal y la Doris no podemos decir, así como así y tan ambiguamente, etcétera.', 'Con la Iris escrita lo que no se percibe es el hedor.', 'Pero es tal la evidencia de la Iris.', 'La Doris le dice que se acerque le muestra dentro. La Cristal se paraliza. Dice: mirá, no pasa nada. Y la mira. Después la Cristal es la única cosa que puede contar de esos días: es breve y tiene forma de triángulo: mirá, no pasa nada, y me mira.'

];

let myFont;
function preload() {
  myFont = loadFont('Inconsolata.ttf');
}


  
 
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  
  // crear objetos
  button = createButton('>> Las exhaustas <<');
  button1 = createButton('<< ingresar >>');
  button.position(50,500);
  button.mousePressed(entrar);
  button.style('font-size', '50px');
  button.style('fontFamily', 'Inconsolata');
  button.style('border-style', 'none');
  button.style('background', 'transparent');
  button.style('color', '#73c29a');

  button1.position(195,550);
  button1.mousePressed(entrar);
  button1.style('font-size', '25px');
  button1.style('fontFamily', 'Inconsolata');
  button1.style('border-style', 'none');
  button1.style('background', 'transparent');
  button1.style('color', 'grey');




  bug1 = new Jitter();
  bug2 = new Jitter();
  bug3 = new Jitter();
  bug4 = new Jitter();

  

   img0 = loadImage('ladoris.png');
   img1 = loadImage('lairma.png');
   img2 = loadImage('lairis.png');
   img3 = loadImage('lacristal.png');

   inconsolata = loadFont('Inconsolata.ttf');
   
   textFont(inconsolata);
   
   texto0 = random(textos);
   texto1 = random(textos);
   texto2 = random(textos);
   texto3 = random(textos);

   color = random(colores);

}

function entrar() {
    window.open('lasexhaustas.html');
  }

function draw() {

    
  background(0);
 
  bug1.move();
  bug1.display();
  bug1.escribiris();
  bug1.serdoris();
  
  

  bug2.move();
  bug2.display();
 // bug2.escribdoris(); 
  bug2.seriris();
  
  bug3.move();
  bug3.display();
  bug3.escribirma();
  bug3.sercristal();
  
  bug4.move();
  bug4.display();
  // bug4.escribcristal();
  bug4.serirma();
  noStroke();

  

  
}





// clase Jitter
class Jitter {
  constructor() {
    this.x = random(-600, 500);
    this.y = random(-200, 50);
    this.diameter = random(75, 150);
    this.speed = 1;
  }

  move() {
    this.x += random(-this.speed, this.speed);
    this.y += random(-this.speed, this.speed);
  }

  display() {
    ellipse(this.x, this.y, this.diameter, this.diameter);
  }

  serdoris(){
    texture(img0);
  }

  seriris(){
    texture(img1);
  }

  serirma(){
    texture(img2);
  }

  sercristal(){
    texture(img3);
  }

  escribiris(){
    
     
        
        textFont(myFont);
        textSize(this.diameter/6);
        
        text(texto0, this.x, this.y + (this.diameter/2 + 4), (1366/2-this.x));
        textWrap(WORD);
        fill(50, 55, 100);
        
       }

       escribdoris () {
    
     
        
        textFont(myFont);
        textSize(this.diameter/6);
        
        text(texto1, this.x, this.y + (this.diameter/2 + 15), (1366/2-this.x));
        fill('hsb(160, 100%, 50%');
        textWrap(WORD);
       
      
       }
//verde #0f0
       escribirma(){
    
     
        
        textFont(myFont);
        textSize(this.diameter/6);
        
        text(texto2, this.x, this.y + (this.diameter/2 + 4), (1366/2-this.x));
        textWrap(WORD);
        fill('#8c3d65');
        
       }

       escribcristal(){
    
     
        
        textFont(myFont);
        textSize(this.diameter/6);
        
        text(texto3, this.x+50, this.y, windowWidth-200);
        textWrap(WORD);
        fill('hsb(160, 100%, 50%');
        
       }
       clicked() {
        window.location.reload();
       }
  }

 
  function mousePressed(){
    bug1.clicked(); 
   }
   

  








  
 

  
